# Generated by Django 4.0.6 on 2022-07-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer1', models.CharField(max_length=200, verbose_name='Вариант1')),
                ('answer2', models.CharField(max_length=200, verbose_name='Вариант2')),
                ('answer3', models.CharField(max_length=200, verbose_name='Вариант3')),
                ('answer4', models.CharField(max_length=200, verbose_name='Вариант4')),
                ('correct', models.CharField(max_length=200, verbose_name='Правильный вариант ответа')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
    ]
