# Generated by Django 4.0.6 on 2022-07-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
