# Generated by Django 4.0.6 on 2022-07-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='images/', width_field=100),
        ),
    ]
