# Generated by Django 4.0.6 on 2022-08-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_article_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
