# Generated by Django 4.0.6 on 2022-08-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_answer1_1_test_answer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer1',
            field=models.CharField(max_length=200, verbose_name='Вариант1'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer2',
            field=models.CharField(max_length=200, verbose_name='Вариант2'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer3',
            field=models.CharField(max_length=200, verbose_name='Вариант3'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer4',
            field=models.CharField(max_length=200, verbose_name='Вариант4'),
        ),
        migrations.AlterField(
            model_name='test',
            name='correct',
            field=models.CharField(max_length=200, verbose_name='Правильный вариант ответа'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
    ]
