# Generated by Django 4.0.6 on 2022-08-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_comment_name_alter_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_img',
            new_name='article_img1',
        ),
        migrations.AddField(
            model_name='article',
            name='article_img2',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
