# Generated by Django 4.0.6 on 2022-08-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_article_img_article_article_img1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author_name',
        ),
    ]
