# Generated by Django 4.0.6 on 2022-08-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_test_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('true1', models.CharField(max_length=200, null=True, verbose_name='Вариант1')),
                ('true2', models.CharField(max_length=200, null=True, verbose_name='Вариант2')),
                ('true3', models.CharField(max_length=200, null=True, verbose_name='Вариант3')),
                ('true4', models.CharField(max_length=200, null=True, verbose_name='Вариант4')),
                ('true5', models.CharField(max_length=200, null=True, verbose_name='Вариант5')),
                ('true6', models.CharField(max_length=200, null=True, verbose_name='Вариант6')),
                ('true7', models.CharField(max_length=200, null=True, verbose_name='Вариант7')),
                ('true8', models.CharField(max_length=200, null=True, verbose_name='Вариант8')),
                ('true9', models.CharField(max_length=200, null=True, verbose_name='Вариант9')),
                ('true10', models.CharField(max_length=200, null=True, verbose_name='Вариант10')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
    ]
