# Generated by Django 4.0.6 on 2022-08-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_truetest_remove_test_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrueTest',
        ),
    ]
