# Generated by Django 4.0.6 on 2022-08-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_choice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
