# Generated by Django 4.0.6 on 2022-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_comment_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(max_length=200, verbose_name='Никнейм'),
        ),
    ]
