# Generated by Django 4.1 on 2022-08-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='choise',
            field=models.CharField(max_length=200, null=True, verbose_name='Choise'),
        ),
    ]
