# Generated by Django 4.1 on 2022-08-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_test_choise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.CharField(max_length=200, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='choice',
            name='ip',
            field=models.CharField(max_length=200, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='choice',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.CharField(max_length=200, null=True, verbose_name='Вопрос'),
        ),
    ]
