# Generated by Django 4.1 on 2022-08-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_choice_choice_text_remove_choice_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.CharField(max_length=200, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='ip',
            field=models.CharField(max_length=200, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='slug',
            field=models.SlugField(),
        ),
    ]
