# Generated by Django 4.1 on 2022-11-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_test_answer5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='choise',
        ),
    ]
