# Generated by Django 4.1 on 2022-11-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_article_pub_date_remove_test_choise'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='article_img1',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
