# Generated by Django 4.1 on 2022-11-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_test_article_img1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='article_img1',
            new_name='img',
        ),
    ]
